package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \ingroup libusb_desc<br>
 * A structure representing the standard USB interface association descriptor.<br>
 * This descriptor is documented in section 9.6.4 of the USB 3.0 specification.<br>
 * All multiple-byte fields are represented in host-endian format.<br>
 * <i>native declaration : include\libusb.h:606</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_interface_association_descriptor extends Structure {
	public byte bLength;
	public byte bDescriptorType;
	public byte bFirstInterface;
	public byte bInterfaceCount;
	public byte bFunctionClass;
	public byte bFunctionSubClass;
	public byte bFunctionProtocol;
	public byte iFunction;
	public libusb_interface_association_descriptor() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bLength", "bDescriptorType", "bFirstInterface", "bInterfaceCount", "bFunctionClass", "bFunctionSubClass", "bFunctionProtocol", "iFunction");
	}
	public libusb_interface_association_descriptor(byte bLength, byte bDescriptorType, byte bFirstInterface, byte bInterfaceCount, byte bFunctionClass, byte bFunctionSubClass, byte bFunctionProtocol, byte iFunction) {
		super();
		this.bLength = bLength;
		this.bDescriptorType = bDescriptorType;
		this.bFirstInterface = bFirstInterface;
		this.bInterfaceCount = bInterfaceCount;
		this.bFunctionClass = bFunctionClass;
		this.bFunctionSubClass = bFunctionSubClass;
		this.bFunctionProtocol = bFunctionProtocol;
		this.iFunction = iFunction;
	}
	public libusb_interface_association_descriptor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_interface_association_descriptor implements Structure.ByReference {
		
	};
	public static class ByValue extends libusb_interface_association_descriptor implements Structure.ByValue {
		
	};
}
