package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \ingroup libusb_desc<br>
 * A structure representing the Container ID descriptor.<br>
 * This descriptor is documented in section 9.6.2.3 of the USB 3.0 specification.<br>
 * All multiple-byte fields, except UUIDs, are represented in host-endian format.<br>
 * <i>native declaration : include\libusb.h:919</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_container_id_descriptor extends Structure {
	public byte bLength;
	public byte bDescriptorType;
	public byte bDevCapabilityType;
	public byte bReserved;
	/** C type : uint8_t[16] */
	public byte[] ContainerID = new byte[16];
	public libusb_container_id_descriptor() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bLength", "bDescriptorType", "bDevCapabilityType", "bReserved", "ContainerID");
	}
	/** @param ContainerID C type : uint8_t[16] */
	public libusb_container_id_descriptor(byte bLength, byte bDescriptorType, byte bDevCapabilityType, byte bReserved, byte ContainerID[]) {
		super();
		this.bLength = bLength;
		this.bDescriptorType = bDescriptorType;
		this.bDevCapabilityType = bDevCapabilityType;
		this.bReserved = bReserved;
		if ((ContainerID.length != this.ContainerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ContainerID = ContainerID;
	}
	public libusb_container_id_descriptor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_container_id_descriptor implements Structure.ByReference {
		
	};
	public static class ByValue extends libusb_container_id_descriptor implements Structure.ByValue {
		
	};
}
