package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \ingroup libusb_desc<br>
 * A collection of alternate settings for a particular USB interface.<br>
 * <i>native declaration : include\libusb.h:713</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_interface extends Structure {
	/** C type : libusb_interface_descriptor* */
	public org.jayhsu.libuvc4java.jna.libusb_interface_descriptor.ByReference altsetting;
	public int num_altsetting;
	public libusb_interface() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("altsetting", "num_altsetting");
	}
	/** @param altsetting C type : libusb_interface_descriptor* */
	public libusb_interface(org.jayhsu.libuvc4java.jna.libusb_interface_descriptor.ByReference altsetting, int num_altsetting) {
		super();
		this.altsetting = altsetting;
		this.num_altsetting = num_altsetting;
	}
	public libusb_interface(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_interface implements Structure.ByReference {
		
	};
	public static class ByValue extends libusb_interface implements Structure.ByValue {
		
	};
}
