package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \ingroup libusb_poll<br>
 * File descriptor for polling<br>
 * <i>native declaration : include\libusb.h:2052</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_pollfd extends Structure {
	public int fd;
	public short events;
	public libusb_pollfd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("fd", "events");
	}
	public libusb_pollfd(int fd, short events) {
		super();
		this.fd = fd;
		this.events = events;
	}
	public libusb_pollfd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_pollfd implements Structure.ByReference {
		
	};
	public static class ByValue extends libusb_pollfd implements Structure.ByValue {
		
	};
}
