package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
import org.jayhsu.libuvc4java.jna.LibusbLibrary.libusb_log_cb;
/**
 * \ingroup libusb_lib<br>
 * Structure used for setting options through \ref libusb_init_context.<br>
 * <i>native declaration : include\libusb.h:1497</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_init_option extends Structure {
	/**
	 * @see libusb_option<br>
	 * C type : libusb_option
	 */
	public int option;
	/** C type : value_union */
	public value_union value;
	/** <i>native declaration : include\libusb.h:1501</i> */
	public static class value_union extends Union {
		public int ival;
		/** C type : libusb_log_cb */
		public libusb_log_cb log_cbval;
		public value_union() {
			super();
		}
		public value_union(int ival) {
			super();
			this.ival = ival;
			setType(Integer.TYPE);
		}
		/** @param log_cbval C type : libusb_log_cb */
		public value_union(libusb_log_cb log_cbval) {
			super();
			this.log_cbval = log_cbval;
			setType(libusb_log_cb.class);
		}
		public value_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends value_union implements Structure.ByReference {
			
		};
		public static class ByValue extends value_union implements Structure.ByValue {
			
		};
	};
	public libusb_init_option() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("option", "value");
	}
	/**
	 * @param option @see libusb_option<br>
	 * C type : libusb_option<br>
	 * @param value C type : value_union
	 */
	public libusb_init_option(int option, value_union value) {
		super();
		this.option = option;
		this.value = value;
	}
	public libusb_init_option(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_init_option implements Structure.ByReference {
		
	};
	public static class ByValue extends libusb_init_option implements Structure.ByValue {
		
	};
}
