package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : include\libusb.h:126</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_cpu_to_le16__tmp_union extends Union {
	/** C type : uint8_t[2] */
	public byte[] b8 = new byte[2];
	public short b16;
	public libusb_cpu_to_le16__tmp_union() {
		super();
	}
	/** @param b8 C type : uint8_t[2] */
	public libusb_cpu_to_le16__tmp_union(byte b8[]) {
		super();
		if ((b8.length != this.b8.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.b8 = b8;
		setType(byte[].class);
	}
	public libusb_cpu_to_le16__tmp_union(short b16) {
		super();
		this.b16 = b16;
		setType(Short.TYPE);
	}
	public libusb_cpu_to_le16__tmp_union(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libusb_cpu_to_le16__tmp_union implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends libusb_cpu_to_le16__tmp_union implements com.sun.jna.Structure.ByValue {
		
	};
}
