package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_still_frame_res extends Structure {
	/** C type : uvc_still_frame_res* */
	public uvc_still_frame_res.ByReference prev;
	/** C type : uvc_still_frame_res* */
	public uvc_still_frame_res.ByReference next;
	public byte bResolutionIndex;
	public short wWidth;
	public short wHeight;
	public uvc_still_frame_res() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("prev", "next", "bResolutionIndex", "wWidth", "wHeight");
	}
	/**
	 * @param prev C type : uvc_still_frame_res*<br>
	 * @param next C type : uvc_still_frame_res*
	 */
	public uvc_still_frame_res(uvc_still_frame_res.ByReference prev, uvc_still_frame_res.ByReference next, byte bResolutionIndex, short wWidth, short wHeight) {
		super();
		this.prev = prev;
		this.next = next;
		this.bResolutionIndex = bResolutionIndex;
		this.wWidth = wWidth;
		this.wHeight = wHeight;
	}
	public uvc_still_frame_res(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_still_frame_res implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_still_frame_res implements Structure.ByValue {
		
	};
}
