package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_input_terminal extends Structure {
	/** C type : uvc_input_terminal* */
	public uvc_input_terminal.ByReference prev;
	/** C type : uvc_input_terminal* */
	public uvc_input_terminal.ByReference next;
	public byte bTerminalID;
	/**
	 * @see uvc_it_type<br>
	 * C type : uvc_it_type
	 */
	public int wTerminalType;
	public short wObjectiveFocalLengthMin;
	public short wObjectiveFocalLengthMax;
	public short wOcularFocalLength;
	public long bmControls;
	public uvc_input_terminal() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("prev", "next", "bTerminalID", "wTerminalType", "wObjectiveFocalLengthMin", "wObjectiveFocalLengthMax", "wOcularFocalLength", "bmControls");
	}
	/**
	 * @param prev C type : uvc_input_terminal*<br>
	 * @param next C type : uvc_input_terminal*<br>
	 * @param wTerminalType @see uvc_it_type<br>
	 * C type : uvc_it_type
	 */
	public uvc_input_terminal(uvc_input_terminal.ByReference prev, uvc_input_terminal.ByReference next, byte bTerminalID, int wTerminalType, short wObjectiveFocalLengthMin, short wObjectiveFocalLengthMax, short wOcularFocalLength, long bmControls) {
		super();
		this.prev = prev;
		this.next = next;
		this.bTerminalID = bTerminalID;
		this.wTerminalType = wTerminalType;
		this.wObjectiveFocalLengthMin = wObjectiveFocalLengthMin;
		this.wObjectiveFocalLengthMax = wObjectiveFocalLengthMax;
		this.wOcularFocalLength = wOcularFocalLength;
		this.bmControls = bmControls;
	}
	public uvc_input_terminal(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_input_terminal implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_input_terminal implements Structure.ByValue {
		
	};
}
