package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_device_descriptor extends Structure {
	public short idVendor;
	public short idProduct;
	public short bcdUVC;
	/** C type : const char* */
	public Pointer serialNumber;
	/** C type : const char* */
	public Pointer manufacturer;
	/** C type : const char* */
	public Pointer product;
	public uvc_device_descriptor() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("idVendor", "idProduct", "bcdUVC", "serialNumber", "manufacturer", "product");
	}
	/**
	 * @param serialNumber C type : const char*<br>
	 * @param manufacturer C type : const char*<br>
	 * @param product C type : const char*
	 */
	public uvc_device_descriptor(short idVendor, short idProduct, short bcdUVC, Pointer serialNumber, Pointer manufacturer, Pointer product) {
		super();
		this.idVendor = idVendor;
		this.idProduct = idProduct;
		this.bcdUVC = bcdUVC;
		this.serialNumber = serialNumber;
		this.manufacturer = manufacturer;
		this.product = product;
	}
	public uvc_device_descriptor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_device_descriptor implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_device_descriptor implements Structure.ByValue {
		
	};
}
