package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_stream_ctrl extends Structure {
	public short bmHint;
	public byte bFormatIndex;
	public byte bFrameIndex;
	public int dwFrameInterval;
	public short wKeyFrameRate;
	public short wPFrameRate;
	public short wCompQuality;
	public short wCompWindowSize;
	public short wDelay;
	public int dwMaxVideoFrameSize;
	public int dwMaxPayloadTransferSize;
	public int dwClockFrequency;
	public byte bmFramingInfo;
	public byte bPreferredVersion;
	public byte bMinVersion;
	public byte bMaxVersion;
	public byte bInterfaceNumber;
	public uvc_stream_ctrl() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bmHint", "bFormatIndex", "bFrameIndex", "dwFrameInterval", "wKeyFrameRate", "wPFrameRate", "wCompQuality", "wCompWindowSize", "wDelay", "dwMaxVideoFrameSize", "dwMaxPayloadTransferSize", "dwClockFrequency", "bmFramingInfo", "bPreferredVersion", "bMinVersion", "bMaxVersion", "bInterfaceNumber");
	}
	public uvc_stream_ctrl(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_stream_ctrl implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_stream_ctrl implements Structure.ByValue {
		
	};
}
