package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_still_ctrl extends Structure {
	public byte bFormatIndex;
	public byte bFrameIndex;
	public byte bCompressionIndex;
	public int dwMaxVideoFrameSize;
	public int dwMaxPayloadTransferSize;
	public byte bInterfaceNumber;
	public uvc_still_ctrl() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bFormatIndex", "bFrameIndex", "bCompressionIndex", "dwMaxVideoFrameSize", "dwMaxPayloadTransferSize", "bInterfaceNumber");
	}
	public uvc_still_ctrl(byte bFormatIndex, byte bFrameIndex, byte bCompressionIndex, int dwMaxVideoFrameSize, int dwMaxPayloadTransferSize, byte bInterfaceNumber) {
		super();
		this.bFormatIndex = bFormatIndex;
		this.bFrameIndex = bFrameIndex;
		this.bCompressionIndex = bCompressionIndex;
		this.dwMaxVideoFrameSize = dwMaxVideoFrameSize;
		this.dwMaxPayloadTransferSize = dwMaxPayloadTransferSize;
		this.bInterfaceNumber = bInterfaceNumber;
	}
	public uvc_still_ctrl(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_still_ctrl implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_still_ctrl implements Structure.ByValue {
		
	};
}
