package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_output_terminal extends Structure {
	/** C type : uvc_output_terminal* */
	public uvc_output_terminal.ByReference prev;
	/** C type : uvc_output_terminal* */
	public uvc_output_terminal.ByReference next;
	public uvc_output_terminal() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("prev", "next");
	}
	/**
	 * @param prev C type : uvc_output_terminal*<br>
	 * @param next C type : uvc_output_terminal*
	 */
	public uvc_output_terminal(uvc_output_terminal.ByReference prev, uvc_output_terminal.ByReference next) {
		super();
		this.prev = prev;
		this.next = next;
	}
	public uvc_output_terminal(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_output_terminal implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_output_terminal implements Structure.ByValue {
		
	};
}
