package org.jayhsu.libuvc4java.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\libuvc.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class uvc_still_frame_desc extends Structure {
	/** C type : uvc_format_desc* */
	public org.jayhsu.libuvc4java.jna.uvc_format_desc.ByReference parent;
	/** C type : uvc_still_frame_desc* */
	public uvc_still_frame_desc.ByReference prev;
	/** C type : uvc_still_frame_desc* */
	public uvc_still_frame_desc.ByReference next;
	/**
	 * @see uvc_vs_desc_subtype<br>
	 * C type : uvc_vs_desc_subtype
	 */
	public int bDescriptorSubtype;
	public byte bEndPointAddress;
	/** C type : uvc_still_frame_res_t* */
	public org.jayhsu.libuvc4java.jna.uvc_still_frame_res.ByReference imageSizePatterns;
	public byte bNumCompressionPattern;
	/** C type : uint8_t* */
	public Pointer bCompression;
	public uvc_still_frame_desc() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("parent", "prev", "next", "bDescriptorSubtype", "bEndPointAddress", "imageSizePatterns", "bNumCompressionPattern", "bCompression");
	}
	/**
	 * @param parent C type : uvc_format_desc*<br>
	 * @param prev C type : uvc_still_frame_desc*<br>
	 * @param next C type : uvc_still_frame_desc*<br>
	 * @param bDescriptorSubtype @see uvc_vs_desc_subtype<br>
	 * C type : uvc_vs_desc_subtype<br>
	 * @param imageSizePatterns C type : uvc_still_frame_res_t*<br>
	 * @param bCompression C type : uint8_t*
	 */
	public uvc_still_frame_desc(org.jayhsu.libuvc4java.jna.uvc_format_desc.ByReference parent, uvc_still_frame_desc.ByReference prev, uvc_still_frame_desc.ByReference next, int bDescriptorSubtype, byte bEndPointAddress, org.jayhsu.libuvc4java.jna.uvc_still_frame_res.ByReference imageSizePatterns, byte bNumCompressionPattern, Pointer bCompression) {
		super();
		this.parent = parent;
		this.prev = prev;
		this.next = next;
		this.bDescriptorSubtype = bDescriptorSubtype;
		this.bEndPointAddress = bEndPointAddress;
		this.imageSizePatterns = imageSizePatterns;
		this.bNumCompressionPattern = bNumCompressionPattern;
		this.bCompression = bCompression;
	}
	public uvc_still_frame_desc(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends uvc_still_frame_desc implements Structure.ByReference {
		
	};
	public static class ByValue extends uvc_still_frame_desc implements Structure.ByValue {
		
	};
}
